# Generated by Django 3.1.2 on 2020-10-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('autor', models.CharField(max_length=200, verbose_name='Autor')),
                ('genero', models.CharField(max_length=200, verbose_name='Autor')),
            ],
        ),
    ]
