# Generated by Django 3.1.2 on 2020-10-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_libros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libros',
            new_name='Libro',
        ),
    ]
